version: '2'
services:
  db:
    image: postgres:9
  node:
    build:
      context: .
      dockerfile: client2/client.dockerfile
    command: npm start
    volumes:
      - .:/code
  web:
    build:
      context: .
      dockerfile: server.dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    links:
      - db
    ports:
      - "8000:8000"
