version: '2'
services:
  db:
    image: postgres:9
  node:
    build:
      context: .
      dockerfile: client.dockerfile
    command: yarn start
    volumes:
      - ./client:/code
    ports:
      - "4201:4201"
  web:
    build:
      context: .
      dockerfile: server.dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    links:
      - db
    ports:
      - "8000:8000"
