# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('approved', 'approved'), ('selected', 'selected')], max_length=20)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=255)),
                ('is_owned', models.NullBooleanField()),
                ('is_in_posession', models.NullBooleanField()),
                ('can_access_for_research', models.NullBooleanField()),
                ('can_loan_temporarily', models.NullBooleanField()),
                ('can_loan_permanent', models.NullBooleanField()),
                ('materials', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('creation', models.TextField(blank=True)),
                ('acquisition', models.TextField(blank=True)),
                ('use', models.TextField(blank=True)),
                ('history2', models.TextField(blank=True)),
                ('significance', models.TextField()),
                ('owner_history', models.TextField(blank=True)),
            ],
        ),
    ]
