# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('approved', 'approved'), ('selected', 'selected')], default='submitted', max_length=20),
        ),
    ]
